server:
  servlet:
    context-path: /getir-book

spring:
  application:
    name: getir-book
  data:
    mongodb:
      database: BookStore
      port: 27017
      host: localhost

getir-book:
  username: test
  password: testpass
  secretKey: JWTGetirBook
  expirationInMs: 86400000

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG